spring.application.name=coreservices

#Postgresql Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-daaltu8n74is73bccoh0-a.ohio-postgres.render.com/taskhubdb_fnsl
spring.datasource.username=postgres_user
spring.datasource.password=sxjw5ocwmbNX8dYAg5niYUOg0f9WvXMa
#JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Port Number
server.port=8001
