spring.application.name=coreservices

#Postgresql Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d8nnqs9o3t8c73d0dmo0-a.oregon-postgres.render.com:5432/taskhub_tm69
spring.datasource.username=postgres_user
spring.datasource.password=1uqEvVqbdjpytPSgeJitkYphidWwYYNw

#JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Port Number
server.port=8001