spring.application.name=coreservices

#Postgresql Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d9q3tgugekts73ceg1ug-a.oregon-postgres.render.com:5432/taskhub_n9gh
spring.datasource.username=postgres_user
spring.datasource.password=9WYYA2ANsbG6M4d6yZN80BWJf57de5kt

#JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Port Number
server.port=8001
